data_source sales:
  type: bigquery
  connection:
    account_info_json_path: /usr/local/airflow/include/gcp/service_account.json
    auth_scopes:
    - https://www.googleapis.com/auth/bigquery
    - https://www.googleapis.com/auth/cloud-platform
    - https://www.googleapis.com/auth/drive
    project_id: 'brave-aviary-428415-v5'
    dataset: sales
soda_cloud:
  host: cloud.us.soda.io
  api_key_id: cb648ff5-fdc4-423b-aaa6-2624e7ef5593
  api_key_secret: wjnPsCLkH2YJB5O4iw-V6i4QtHqctG9JF7vkApVCxM9VSjp9TGXMew